name: bus-ticket自动构建部署
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取最新代码
        uses: actions/checkout@v3
      - name: 设置JDK8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  
          java-version: '8'
          cache: 'maven'
      - name: 项目打包
        run: cd ticket-platform && mvn -B package
      - name: 上传jar包
        run: sshpass -p ${{secrets.TENCENT_PASSWORD}} scp ./ticket-platform/target/ticket-platform-0.0.1-SNAPSHOT.jar ${{secrets.TENCENT_USERNAME}}@${{vars.TENCENT_IP}}:/data/bus-ticket/docker-build/apps
      - name: 触发服务器上的deploy脚本
        run: sshpass -p ${{secrets.TENCENT_PASSWORD}} ssh ${{secrets.TENCENT_USERNAME}}@${{vars.TENCENT_IP}} "cd /data/bus-ticket/docker-build/apps && mv -f ticket-platform-0.0.1-SNAPSHOT.jar ticket-platform.jar && deploy"
